# Версия docker-compose
version: '3.8'
# Список наших сервисов (контейнеров)
services:
   nginx:
      # используем последний стабильный образ nginx
      build: ./images/nginx
      container_name: 'resume_nginx'
      # маршрутизируем порты
      ports:
         - '8301:80'
      # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
      volumes:
         - ./resume_backend:/var/www/resume_backend
         - ./hosts:/etc/nginx/conf.d
         - ./logs:/var/log/nginx
      # nginx должен общаться с php контейнером
      links:
         - php73
   php73:
      # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
      build: ./images/php73
      container_name: 'resume_php73'
      # этот образ будет общаться с mysql
      links:
         - mariadb
         - mailhog
      # монтируем директорию с проектами
      volumes:
         - ./resume_backend:/var/www/resume_backend
      environment:
         XDEBUG_CONFIG: 'remote_host=192.168.220.1 remote_enable=1'
         PHP_IDE_CONFIG: 'serverName=Docker'
   mariadb:
      image: mariadb:latest
      container_name: 'resume_mariadb'
      ports:
         - '8302:3306'
      volumes:
         - ./database:/var/lib/mysql
      # задаем пароль для root пользователя
      environment:
         MYSQL_ROOT_PASSWORD: root
   phpmyadmin:
      image: phpmyadmin:latest
      container_name: 'resume_pma'
      links: 
         - mariadb
      ports:
         - '8303:80'
      environment:
         - PMA_HOST=mariadb
         - UPLOAD_LIMIT=40M
   mailhog:
      image: mailhog/mailhog:latest
      container_name: 'resume_mailhog'
      ports:
         - '8304:1025'
         - '8305:8025'
